spring:
  # datasource:
  #   url: jdbc:postgresql://localhost:5432/dataMapping
  #   username: postgres
  #   password: postgres
  #   driver-class-name: org.postgresql.Driver
  # jpa:
  #   hibernate:
  #     ddl-auto: update
  #   show-sql: false
  #   database-platform: org.hibernate.dialect.PostgreSQLDialect
  # cloud:
  #   compatibility-verifier:
  #     enabled: false

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost
    
    
microservice:
  payment-service:
    endpoints:
      endpoint:
        uri: http://PAYMENT-SERVICE/payment/doPayment
  order-service:
    endpoints:
      endpoint:
        uri: http://ORDER-SERVICE/order/bookOrder    
